[[language]]
name = "markdown"
language-servers = [ "marksman", "markdown-oxide", "vscode-html-language-server" ]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = 'prettier', args = ["--parser", "yaml", "--quote-props", "consistent"] }

[[language]]
name = "xml"
auto-format = true
formatter = { command = 'prettier', args = ["--plugin", "@prettier/plugin-xml", "--tab-width", "2", "--xml-whitespace-sensitivity", "ignore"] }
